### ISSUE TITLE
Wrong readme instructions 

### ISSUE THREAD

**Issue by gabrielperales** [kofno/BasicLambda#2]
I'm a newbie with Purescript, and I want to use purescript for coding some AWS lambda functions, so I'm trying to run your code but seems like there are some errors in the code. `pulp dep` seems to be deprecated, and also when I tried to build the package the compiler raise some errors.

**Comment by kofno** [comment]
It's possible. This repo hasn't been updated in a while. I'll try to find some time to update it for the latest. Of course, if you figure it out, PRs are graciously accepted :)

**Comment by gabrielperales** [comment]
I'm trying to make it work, but I don't know if I'm going to be able to PR this repo. I just started to learn PureScript.

**Comment by kofno** [comment]
No worries!

**Comment by gabrielperales** [comment]
@kofno can you check the pull request I did? Thank you!

**Comment by kofno** [comment]
Yes. I’ll take a look when I get a chance. Sorry for the delay.

**Comment by kofno** [comment]
I think things are working now.
